name: Parallel Test Run
on: push
jobs:
  add-to-cart-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Install npm dependencies, cache them correctly
      # and run all Cypress tests

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:addToCart

      - name: Add to cart Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Mochawesome html report - Add to cart
          path: cypress/reports/html

      - name: HTML Preview - Add to cart
        id: html_preview
        uses: pavi2410/html-preview-action@v2
        with:
          html_file: 'cypress/reports/html/index.html'

  register-flow-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Install npm dependencies, cache them correctly
      # and run all Cypress tests

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:registerTest

      - name: Register Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Mochawesome html report - Register
          path: cypress/reports/html

      - name: HTML Preview - Register test
        id: html_preview
        uses: pavi2410/html-preview-action@v2
        with:
          html_file: 'cypress/reports/html/index.html'