name: Parallel Test Run
on: push
jobs:
  ui-tests-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Install npm dependencies, cache them correctly
      # and run all Cypress tests

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:uiTests

      - name: Add to cart Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Mochawesome html report - All UI Tests
          path: cypress/reports/html

  api-tests-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Install npm dependencies, cache them correctly
      # and run all Cypress tests

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:apiTests

      - name: All apis Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Mochawesome html report - All Api Tests
          path: cypress/reports/html

